### ISSUE TITLE
Allow using dependencies

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape-cairo#4]
### Overview

Allow the user to import their cairo dependencies in their cairo smart-contract

### Specification

If the user has specified dependencies like this:
```yaml
dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/cairo-contracts
    version: 0.1.0
    contracts_folder: src
```

Allow them to import those dependencies in like this:

```cairo
from openzeppelin.utils.constants import INVALID_ID, IERC165_ID
```

Remember, your feature is much more likely to be included if it does not involve any breaking changes.

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.
